name: Terraform Plan Check

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'terraform/env/dev/**'
      - 'terraform/env/stg/**'
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-dev:
    if: ${{ contains(github.event.pull_request_target.changes, 'terraform/env/dev/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::351049001406:role/GithubActionRole'
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        run: |
          cd terraform/env/dev
          terraform init

      - name: Validate Terraform configuration
        run: |
          cd terraform/env/dev
          terraform validate

      - name: Plan Terraform changes
        id: plan
        run: |
          cd terraform/env/dev
          terraform plan -out=tfplan.binary

  terraform-stg:
    if: ${{ contains(github.event.pull_request_target.changes, 'terraform/env/stg/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::351049001406:role/GithubActionRole'
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        run: |
          cd terraform/env/stg
          terraform init

      - name: Validate Terraform configuration
        run: |
          cd terraform/env/stg
          terraform validate

      - name: Plan Terraform changes
        id: plan
        run: |
          cd terraform/env/stg
          terraform plan -out=tfplan.binary