name: TFLint Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - terraform/env/dev
          - terraform/env/stg

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Show TFLint version
        run: tflint --version
        working-directory: ${{ matrix.env }}

      - name: Initialize TFLint plugins
        run: tflint --init
        working-directory: ${{ matrix.env }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: tflint -f compact
        working-directory: ${{ matrix.env }}
